// Tipo => Funcion: 1 Tematica: 2
var PRCollection = {
    "conativo": {
        "tipo": 1,
        "prioridad": 3,
        "palabras": [
            "Vamos",
            "Veamos",
            "Leamos",
            "invito",
            "hagamos",
            "cambiemos",
            "vayamos",
            "asistamos",
            "gritemos",
            "cuidemos",
            "asistan",
            "vayan",
            "Nuestro",
            "vengan",
            "cambiando",
            "acompáñanos",
            "avísales",
            "firma",
            "consulta",,
            "bajemos",
            "súmate",
            "regístrate",
            "convence",
            "donar",
            "apoyar",
            "queremos",
            "escuchar",
            "vengan",
            "recomendamos",
            "comparte",
            "escuchar",
            "ayuda",
            "necesitan",
            "entra",
            "dejes",
            "puedas",
            "invitamos"
        ]
    },

    "efemeride": {
        "tipo": 2,
        "prioridad": 2,
        "palabras": [
            "desde",
            "hace",
            "conmemoremos",
            "celebra",
            "día",
            "mundial",
            "conmemora",
            "años",
            "mes",
            "reconocer",
            "nació",
            "decreto",
            "septiembre",
            "noviembre",
            "muchas",
            "felicidades",
            "recordamos",
            "recuerda",
            "creación",
            "defendamos",
            "deseo",
            "fechas",
            "deseamos"
        ]
    },

    "emotivo": {
        "tipo": 1,
        "prioridad": 2,
        "palabras": [
            "Siento",
            "Me",
            "enojo",
            "honra",
            "alegra",
            "molesta",
            "enorgullece",
            "amo",
            "feliz",
            "felicidades",
            "deseamos",
            "nerviosos",
            "emocionados",
            "somos",
            "orgulloso",
            "contento",
            "agradezco",
            "lamento",
            "solidaridad",
            "unidos",
            "apoyo",
            "esforzarnos",
            "orgullo",
            "unidos",
            "darlo",
            "te",
            "quiero",
            "amo",
            "extraño",
            "estoy",
            "seguro",
            "feliz",
            "enojado",
            "triste",
            "triunfamos",
            "anonadados",
            "estupefactos",
            "¡",
            "advertimos",
            "engañados",
            "indigna",
            "inconcebible",
            "enfadó",
            "defenderemos",
            "venganza",
            "promiscuidad",
            "deshonesto",
            "sentimientos",
            "equivoqué",
            "felicidad",
            "gracias",
            "agradecido",
            "!"
        ]
    },

    "fatico": {
        "tipo": 1,
        "prioridad": 4,
        "palabras": [
            "cómo te ha ido",
            "cómo están",
            "sí",
            "claro",
            "podemos",
            "pues",
            "hola",
            "qué",
            "adios",
            "nos vemos",
            "hay"
        ]
    },

    "metalinguistico":{
        "tipo": 1,
        "prioridad": 6,
        "palabras": [
            "significa",
            "sirve",
            "explicar",
            "entender",
            "Permite"
        ]
    },

    "personal": {
        "tipo": 2,
        "prioridad": 4,
        "palabras": [
            "juntos",
            "momentos",
            "compañera",
            "vida",
            "soy",
            "pienso",
            "celebrando",
            "Beatriz",
            "Erika",
            "Martha"
        ]
    },

    "poetico": {
        "tipo": 1,
        "prioridad": 5,
        "palabras": [
            "ejemplo",
            "escuchar",
            "razones",
            "soltarnos",
            "nunca",
            "bello",
            "pena",
            "toda",
            "curules",
            "manos",
            "reemplazarles",
            "ardid",
            "subterfugio"
        ]
    },

    "politico": {
        "tipo": 2,
        "prioridad": 1,
        "palabras": [
            "coyuntura",
            "gobierno",
            "PAN",
            "PRI",
            "MORENA",
            "Frente",
            "Ciudadano",
            "partido",
            "acción",
            "nacional",
            "democrático",
            "política",
            "gobernabilidad",
            "poder",
            "cambio",
            "elección",
            "voto",
            "firmas",
            "ciudadanos",
            "democracia",
            "Presidencia",
            "honestidad",
            "transparencia",
            "candidato",
            "votar",
            "Consejo",
            "opositor",
            "campaña",
            "constitución",
            "político-electoral",
            "recorrido",
            "violencia",
            "continuidad",
            "gobernador",
            "municipio",
            "honrados",
            "trabajadores",
            "seguridad",
            "pública",
            "nación",
            "pobreza",
            "estudio",
            "trabajo",
            "dinero",
            "adicciones",
            "drogas",
            "marginados",
            "Margarita",
            "Zavala",
            "Calderón",
            "EPN",
            "Fiscal",
            "General",
            "República"
        ]
    },

    "referencial": {
        "tipo": 1,
        "prioridad": 1,
        "palabras": [
            "Hoy",
            "recordamos",
            "sucedió",
            "fue",
            "día",
            "conmemoración",
            "aniversario",
            "nació",
            "natalicio",
            "reconocido",
            "implica",
            "conocí",
            "incapaces",
            "hoy"
        ]
    },

    "social": {
        "tipo": 2,
        "prioridad": 3,
        "palabras": [
            "solidarios",
            "#FuerzaMexico",
            "solidaridad",
            "unidos",
            "apoyo",
            "esforzarnos",
            "apoyandonos",
            "adversidad",
            "dejaremos",
            "lluvia",
            "terremoto",
            "sismo",
            "ayudar",
            "afectados",
            "ayudando",
            "salvar",
            "soltar",
            "vidas",
            "recuperar",
            "hacerlo",
            "llegar",
            "solidaridas",
            "sumándonos",
            "colecta",
            "acopio",
            "emergencia",
            "damnificados",
            "fideicomiso",
            "sismos",
            "apoyar",
            "tragedia"
        ]
    }
}